"""Data models for RAG pipeline tracing.

Defines the :class:`TraceRecord` and :class:`FeedbackUpdate` dataclasses
used across all tracing providers.  These are plain dataclasses (not Pydantic)
to keep the tracing package dependency-free.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone


@dataclass
class TraceRecord:
    """A single RAG pipeline trace capturing one query-response cycle.

    Created by the pipeline during ``process_query()`` with retrieval data,
    then enriched by the application layer with the LLM response and latency,
    and optionally updated with user feedback.
    """

    # ── Identity ──

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    """Unique trace identifier (UUID4)."""

    session_id: str | None = None
    """Groups turns within a single conversation session."""

    user_id: str | None = None
    """Identifies the user (multi-user deployments)."""

    # ── Timestamps ──

    created_at: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc),
    )
    """When the trace was created (query time)."""

    response_at: datetime | None = None
    """When the LLM response completed."""

    # ── RAG pipeline data (logged by pipeline) ──

    query: str = ""
    """The user's original query."""

    expanded_queries: list[str] = field(default_factory=list)
    """Query variants generated by expansion (empty when expansion is disabled)."""

    retrieved_chunks: list[dict] = field(default_factory=list)
    """Chunks returned by search (serialised :class:`RetrievedChunk` dicts)."""

    reranked_chunks: list[dict] = field(default_factory=list)
    """Chunks after reranking (empty when reranking is disabled)."""

    formatted_context: str = ""
    """The assembled context string injected into the LLM prompt."""

    collection_ids: list[int] = field(default_factory=list)
    """Albert collection IDs searched."""

    # ── LLM data (logged by app after generation) ──

    response: str | None = None
    """The LLM's generated answer."""

    model: str = ""
    """Model alias used for generation (e.g. ``openweight-medium``)."""

    temperature: float = 0.0
    """Temperature setting used for generation."""

    latency_ms: int | None = None
    """Total response latency in milliseconds (query to response end)."""

    # ── Config snapshot (logged at query time) ──

    config_snapshot: dict = field(default_factory=dict)
    """Full ``ragfacile.toml`` config as dict at the time of the query."""

    # ── User feedback (logged by app on user action) ──

    feedback_score: int | None = None
    """User satisfaction score (e.g. 1-5 stars, or +1/-1 thumbs)."""

    feedback_tags: list[str] = field(default_factory=list)
    """Structured feedback tags (e.g. ``["irrelevant", "incomplete"]``)."""

    feedback_comment: str | None = None
    """Free-text feedback from the user."""


@dataclass
class FeedbackUpdate:
    """Partial update for adding user feedback to an existing trace."""

    score: int | None = None
    tags: list[str] = field(default_factory=list)
    comment: str | None = None
