"""RAG Facile chat agent tools.

Each @tool is callable by the smolagents ToolCallingAgent during a chat session.
The workspace root is set once at session start by the agent harness.
"""

import subprocess
from pathlib import Path

from smolagents import tool

# ── Docs index ────────────────────────────────────────────────────────────────
# Maps topic keywords to doc paths relative to the docs root.
# Keys are lowercase — matched against lowercased user query.

_DOCS_INDEX: dict[str, str] = {
    # Guides
    "getting started": "guides/getting-started.md",
    "setup": "guides/getting-started.md",
    "install": "guides/getting-started.md",
    "rag": "guides/how-rag-works.md",
    "how rag works": "guides/how-rag-works.md",
    "pipeline": "guides/rag-pipeline.md",
    "evaluation": "guides/evaluation.md",
    "eval": "guides/evaluation.md",
    "proxy": "guides/proxy-setup.md",
    "uninstall": "guides/uninstalling.md",
    "windows": "guides/windows-setup.md",
    # Reference
    "config": "reference/ragfacile-toml.md",
    "configuration": "reference/ragfacile-toml.md",
    "ragfacile.toml": "reference/ragfacile-toml.md",
    "toml": "reference/ragfacile-toml.md",
    "preset": "reference/ragfacile-toml.md",
    "components": "reference/components.md",
    "packages": "reference/components.md",
    "science": "reference/rag-science.md",
    "research": "reference/rag-science.md",
    "chunking": "reference/rag-science.md",
    "embedding": "reference/rag-science.md",
    "reranking": "reference/rag-science.md",
    "retrieval": "reference/rag-science.md",
}


# Module-level workspace reference — set by the agent harness at session start.
_workspace_root: Path | None = None


def set_workspace_root(root: Path | None) -> None:
    """Register the workspace root so tools can locate project files."""
    global _workspace_root
    _workspace_root = root


@tool
def get_ragfacile_config() -> str:
    """Read the current ragfacile.toml configuration.

    Use this to answer questions about the RAG pipeline settings such as
    which preset is active, retrieval parameters, collection IDs, etc.
    """
    if _workspace_root is None:
        return (
            "No workspace detected — ragfacile.toml was not found in the current "
            "directory or any parent directory. "
            "Run 'rag-facile setup' to create a workspace."
        )
    config_file = _workspace_root / "ragfacile.toml"
    if not config_file.exists():
        return (
            "No ragfacile.toml found in this workspace. "
            "Run 'rag-facile setup' to create one."
        )
    return config_file.read_text(encoding="utf-8")


@tool
def get_agents_md() -> str:
    """Read AGENTS.md from the workspace — the project architecture guide.

    Use this to answer questions about the project structure, available packages,
    CLI commands, coding conventions, or how the RAG pipeline is organised.
    """
    if _workspace_root is None:
        return "No workspace detected. Run 'rag-facile setup' to create a workspace."
    agents_file = _workspace_root / "AGENTS.md"
    if not agents_file.exists():
        return (
            "No AGENTS.md found in this workspace. "
            "This file is generated by 'rag-facile setup' and describes the project "
            "architecture. It may be missing if the workspace was created manually."
        )
    return agents_file.read_text(encoding="utf-8")


@tool
def get_recent_git_activity() -> str:
    """Show the last 15 git commits in the workspace.

    Use this to answer questions about what changed recently, what the user
    has been working on, or whether the project is up to date.
    """
    if _workspace_root is None:
        return "No workspace detected. Run 'rag-facile setup' to create a workspace."
    try:
        result = subprocess.run(
            [
                "git",
                "log",
                "--oneline",
                "--decorate",
                "--no-merges",
                "-15",
            ],
            cwd=_workspace_root,
            capture_output=True,
            text=True,
            check=True,
        )
        output = result.stdout.strip()
        return output if output else "No commits found in this repository yet."
    except FileNotFoundError:
        return "git is not installed or not available on PATH."
    except subprocess.CalledProcessError as exc:
        return f"git log failed: {exc.stderr.strip()}"


def _get_docs_dir() -> Path | None:
    """Return the bundled docs directory, or None if not found."""
    # Installed package: docs bundled at cli/docs/
    bundled = Path(__file__).resolve().parent.parent / "docs"
    if bundled.exists():
        return bundled
    # Development: docs live at repo root docs/
    repo_root = Path(__file__).resolve().parents[5]
    local = repo_root / "docs"
    if local.exists():
        return local
    return None


@tool
def get_docs(topic: str) -> str:
    """Read rag-facile documentation on a given topic.

    Use this when the user asks about RAG concepts, configuration, setup,
    evaluation, or any rag-facile feature. Pass an empty string to list
    all available documents.

    Args:
        topic: Keyword to look up, e.g. 'rag', 'preset', 'evaluation',
               'chunking', 'getting started', 'pipeline'. Empty string
               returns the full index of available docs.
    """
    docs_dir = _get_docs_dir()
    if docs_dir is None:
        return "Documentation not found. This may be a packaging issue."

    # Empty topic → return index of available docs
    if not topic.strip():
        lines = ["Available rag-facile documentation:\n"]
        for key, path in sorted(_DOCS_INDEX.items()):
            lines.append(f"  - {key!r} → {path}")
        return "\n".join(lines)

    # Find best match by checking each keyword against the topic
    topic_lower = topic.lower()
    matched_path: str | None = None
    for keyword, path in _DOCS_INDEX.items():
        if keyword in topic_lower or topic_lower in keyword:
            matched_path = path
            break

    if matched_path is None:
        available = ", ".join(f"'{k}'" for k in sorted(_DOCS_INDEX))
        return f"No documentation found for '{topic}'. Available topics: {available}."

    doc_file = docs_dir / matched_path
    if not doc_file.exists():
        return f"Documentation file '{matched_path}' is missing from this installation."

    return doc_file.read_text(encoding="utf-8")
